---
- name: VM from template
  hosts: all
  #hosts: localhost
  gather_facts: false
#  connection: local
  become: yes
  vars:
    vcenter: myventer.mydomain
    username: DOMAIN\User
    passwd: password
    datacenter: MyDataCenter
    cluster: mycluster
    folder: /vm/Lab
    name: newvm001
    guest_os: rhel7_64Guest
    datastore: mydatastore_cluster
    disk_size : 10
    memory: 2048
    cpu: 2
    net: My net
    mac: 00:00:00:00:00:00
  tasks:
  - name: create the VM from Template
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ username }}"
      password: "{{ passwd }}"
      validate_certs: no
      datacenter: "{{ datacenter }}"
      cluster: "{{ cluster }}"
      folder: "{{ folder }}"
      name: "{{ name }}"
      name_match: first
      state: present
      guest_id: "{{ guest_os }}"
      disk:
      - size_gb: "{{ disk_size }}"
        type: thick
        datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
        scsi: paravirtual
      networks:
      - name: "{{ net }}"
        device_type: vmxnet3
        mac: "{{ mac }}"
      template: MYTEMPLATE
      wait_for_ip_address: no
    register: deploy
